### ISSUE TITLE
Jandax fail when using java modularity (JPMS)

### ISSUE THREAD

**Issue by apssouza22** [vlsi/vlsi-release-plugins#86]
It seems that the plugin can not deal with the module-info.class from the JPMS

```
Execution failed for task ':platform:runtime:quarkus:base:jandexMain'.
> com.github.vlsi.jandex.JandexException: Unable to process 1 file. It might be caused by invalid bytecode in the class file or a defect in org.jboss:jandex; You might analyze the bytecode with the following command: javap -verbose -p <ClassName.class>; Unable to parse the following file: /Users/alexsandro.souza/code/lodestar/platform/runtime/quarkus/base/build/classes/java/main/module-info.class

```

**Comment by vlsi** [comment]
Can you attach the problematic file? Does it happen for every module-info.class?

**Comment by apssouza22** [comment]
@vlsi Yes. Any module-info. class


```
module lodestar.platform.quarkus.base {
  requires static jakarta.cdi;

  requires arc;
  requires smallrye.config.core;

  exports com.company.lodestar.platform.quarkus.base.config;
}

```

**Comment by apssouza22** [comment]
I also tried with this project https://github.com/jjohannes/gradle-project-setup-howto

**Comment by apssouza22** [comment]
Hi @vlsi please approve the fix for the issue https://github.com/vlsi/vlsi-release-plugins/pull/87

**Comment by vlsi** [comment]
The workaround seems to add an updated dependency to `jandexClasspath` configuration explicitly:

```kotlin
dependencies {
    jandexClasspath("io.smallrye:jandex:3.0.5")
}
```

I'm currently updating https://github.com/autostyle/autostyle to Java 17 / Gradle 8.5, then I will proceed with Java 17 / Gradle 8.5 for https://github.com/vlsi/vlsi-release-plugins, so the release for vlsi-release-plugins could take a bit of time. Hopefully, the workaround should be good enough.

**Comment by apssouza22** [comment]
@vlsi where should I add the dependency declaration? Along with the other plugins? Something like below?

dependencies {
   implementation("com.github.vlsi.gradle:jandex-plugin:1.90")
    jandexClasspath("io.smallrye:jandex:3.0.5")
}

**Comment by vlsi** [comment]
Exactly
